const LOCALES = {
  en: {
    pageTitle: "SpoTracker - Your Spotify Wrapped, Every Day",
    pageDescription: "SpoTracker tracks your Spotify listening habits offline, giving you detailed reports with top artists, top tracks, and listening patterns - whenever you want, not just once a year.",
    navFeatures: "Features",
    navObjections: "Objections",
    navFaq: "FAQ",
    navAbout: "About",
    navDownload: "Free Download",
    heroProof: "Open source \u00b7 100% free \u00b7 No account needed",
    heroTitle1: "Your Spotify Wrapped.",
    heroTitle2: "Every single day.",
    heroSub: "A tiny app that tracks every song you play on Spotify, and generates beautiful reports you can explore anytime - not just in December.",
    heroCta: "See your listening stats - free",
    heroSource: "View source code",
    heroNote: "Windows 10/11 \u00b7 Installs in 30 seconds",
    mockTitle: "SpoTracker - Overview Report",
    mockListening: "Total listening",
    mockArtists: "Distinct artists",
    mockPlays1: "47 plays",
    mockPlays2: "38 plays",
    mockPlays3: "31 plays",
    featuresTitle: "How it works",
    featuresSub: "Install it once. SpoTracker handles the rest.",
    feat1Title: "Tracks automatically",
    feat1Desc: "Detects what's playing on Spotify in real time. No manual input - just listen to music as you normally do.",
    feat2Title: "Generates visual reports",
    feat2Desc: "One click generates an HTML report with your top tracks, top artists, plays per weekday, and recent activity.",
    feat3Title: "Stays on your computer",
    feat3Desc: "All data is stored locally as a CSV file. No accounts, no servers, no cloud sync. Your music habits are yours alone.",
    feat4Title: "Uses almost no resources",
    feat4Desc: "~15 MB of RAM. 0% CPU. Lighter than a browser tab. You'll forget it's there.",
    feat5Title: "Starts with Windows",
    feat5Desc: "Runs at startup automatically. Install once, then check your stats whenever you're curious.",
    feat6Title: "Data you can export",
    feat6Desc: "Your listening history is a plain CSV file. Open it in Excel, import it into Python, or build your own dashboards.",
    screenshotsTitle: "See it in action",
    screenshotsSub: "Real reports generated by SpoTracker. This is what your data looks like.",
    screenshotCap1: "Overview - your listening stats at a glance",
    screenshotCap2: "Tracks - every song you've listened to",
    screenshotCap3: "Top Artists - ranked by listening time",
    objTitle: "You might be thinking\u2026",
    objSub: "Fair questions. Here are honest answers.",
    objQ1: "\"Is it safe? Windows Defender flagged it.\"",
    objA1: "That warning appears for any unsigned open-source app. The full source code is on GitHub - every line is inspectable. SpoTracker doesn't connect to the internet and doesn't modify Spotify.",
    objQ2: "\"Why not just wait for Spotify Wrapped?\"",
    objA2: "Wrapped gives you a fun summary once a year. SpoTracker gives you detailed, track-level data every single day - how many minutes per artist, which songs you skip, your listening patterns by weekday.",
    objQ3: "\"Does it need my Spotify login?\"",
    objA3: "No. SpoTracker reads the Spotify window title to detect what's playing. No API keys, no OAuth, no passwords. It works with both Free and Premium accounts.",
    objQ4: "\"Will it slow down my PC?\"",
    objA4: "It uses ~15 MB RAM and 0% CPU. For comparison, a single Chrome tab uses 5-10x more. You won't notice it's running.",
    proofTitle: "Built in the open",
    proofSub: "Everything about SpoTracker is transparent and free.",
    proofLabel1: "Open source code",
    proofLabel2: "Data sent to the cloud",
    proofLabel3: "Forever, no premium tiers",
    proofValue3: "Free",
    faqTitle: "Frequently asked",
    faqSub: "Quick answers to the remaining questions.",
    faqQ1: "Where is my data stored?",
    faqA1: "In your Documents folder at <code>C:\\Users\\&lt;you&gt;\\Documents\\SpoTracker\\</code>. The listening history is <code>music-list.csv</code> and reports go into the <code>reports</code> subfolder.",
    faqQ2: "Does it track accurately when I pause?",
    faqA2: "Yes. SpoTracker detects when Spotify is paused and subtracts the paused time automatically. It also filters short plays (under 20 seconds) in reports.",
    faqQ3: "Does it work on Mac or Linux?",
    faqA3: "Currently Windows-only (10 and 11). It uses Windows APIs to read window titles and display the tray icon.",
    faqQ4: "Can I uninstall it completely?",
    faqA4: "Yes, uninstall like any Windows app through Settings \u2192 Apps. Your listening data in Documents is preserved so you don't lose your history.",
    faqQ5: "How do I generate a report?",
    faqA5: "Right-click the SpoTracker icon in your system tray (bottom-right corner) and select \"Generate New Report\". Your browser will open with the results.",
    ctaTitle: "Your listening stats are waiting",
    ctaSub: "Find out what your music says about you.",
    ctaCheck1: "Installs in 30 seconds",
    ctaCheck2: "No account required",
    ctaCheck3: "Free forever",
    ctaBtn: "Download SpoTracker - it's free",
    founderTitle: "Why I built this",
    founderP1: "I love music. I listen to Spotify for hours every day. But I had no idea what I actually listened to - until Wrapped came out in December, and even then it was just a highlight reel.",
    founderP2: "I wanted to know the real numbers. How many minutes did I spend with each artist? Which songs did I skip? What days do I listen the most? And I wanted to check whenever I felt like it, not once a year.",
    founderP3: "So I built SpoTracker. A tiny app that runs in the background, tracks everything locally, and gives me beautiful reports on demand. No cloud, no accounts, no data leaving my computer.",
    founderP4: "If you're the kind of person who checks their Wrapped screenshots months later, this is for you.",
    founderRole: "Developer & music enthusiast",
    footer: "SpoTracker - Open source on <a href=\"https://github.com/andreferreira04/spoTracker\" target=\"_blank\" rel=\"noopener\">GitHub</a>. Made with \u266a by Andr\u00e9 Ferreira."
  },

  pt: {
    pageTitle: "SpoTracker - O teu Spotify Wrapped, todos os dias",
    pageDescription: "O SpoTracker regista os teus h\u00e1bitos de escuta no Spotify offline, gerando relat\u00f3rios detalhados com top artistas, top m\u00fasicas e padr\u00f5es de escuta - quando quiseres, n\u00e3o apenas uma vez por ano.",
    navFeatures: "Funcionalidades",
    navObjections: "D\u00favidas",
    navFaq: "FAQ",
    navAbout: "Sobre",
    navDownload: "Download Gr\u00e1tis",
    heroProof: "Open source \u00b7 100% gr\u00e1tis \u00b7 Sem conta necess\u00e1ria",
    heroTitle1: "O teu Spotify Wrapped.",
    heroTitle2: "Todos os dias.",
    heroSub: "Uma pequena app que regista todas as m\u00fasicas que ouves no Spotify e gera relat\u00f3rios bonitos que podes explorar a qualquer momento - n\u00e3o apenas em dezembro.",
    heroCta: "V\u00ea as tuas estat\u00edsticas - gr\u00e1tis",
    heroSource: "Ver c\u00f3digo fonte",
    heroNote: "Windows 10/11 \u00b7 Instala em 30 segundos",
    mockTitle: "SpoTracker - Relat\u00f3rio Geral",
    mockListening: "Tempo total",
    mockArtists: "Artistas distintos",
    mockPlays1: "47 plays",
    mockPlays2: "38 plays",
    mockPlays3: "31 plays",
    featuresTitle: "Como funciona",
    featuresSub: "Instala uma vez. O SpoTracker trata do resto.",
    feat1Title: "Regista automaticamente",
    feat1Desc: "Deteta o que est\u00e1 a tocar no Spotify em tempo real. Sem input manual - ouve m\u00fasica como sempre.",
    feat2Title: "Gera relat\u00f3rios visuais",
    feat2Desc: "Um clique gera um relat\u00f3rio HTML com as tuas top m\u00fasicas, top artistas, plays por dia da semana, e atividade recente.",
    feat3Title: "Fica no teu computador",
    feat3Desc: "Todos os dados ficam guardados localmente num ficheiro CSV. Sem contas, sem servidores, sem cloud. Os teus h\u00e1bitos musicais s\u00e3o s\u00f3 teus.",
    feat4Title: "Quase sem recursos",
    feat4Desc: "~15 MB de RAM. 0% CPU. Mais leve que um separador do browser. Vais esquecer que est\u00e1 ali.",
    feat5Title: "Inicia com o Windows",
    feat5Desc: "Corre no arranque automaticamente. Instala uma vez e consulta as tuas estat\u00edsticas quando quiseres.",
    feat6Title: "Dados export\u00e1veis",
    feat6Desc: "O teu hist\u00f3rico de escuta \u00e9 um ficheiro CSV simples. Abre no Excel, importa em Python, ou cria os teus pr\u00f3prios dashboards.",
    screenshotsTitle: "V\u00ea em a\u00e7\u00e3o",
    screenshotsSub: "Relat\u00f3rios reais gerados pelo SpoTracker. \u00c9 assim que os teus dados ficam.",
    screenshotCap1: "Vis\u00e3o geral - as tuas estat\u00edsticas de escuta",
    screenshotCap2: "M\u00fasicas - todas as m\u00fasicas que ouviste",
    screenshotCap3: "Top Artistas - ordenados por tempo de escuta",
    objTitle: "Podes estar a pensar\u2026",
    objSub: "Perguntas justas. Respostas honestas.",
    objQ1: "\"É seguro? O Windows Defender deu alerta.\"",
    objA1: "Esse aviso aparece para qualquer app open-source n\u00e3o assinada. O c\u00f3digo fonte completo est\u00e1 no GitHub - cada linha \u00e9 verific\u00e1vel. O SpoTracker n\u00e3o se liga \u00e0 internet nem modifica o Spotify.",
    objQ2: "\"Porqu\u00ea n\u00e3o esperar pelo Spotify Wrapped?\"",
    objA2: "O Wrapped d\u00e1-te um resumo divertido uma vez por ano. O SpoTracker d\u00e1-te dados detalhados, ao n\u00edvel da m\u00fasica, todos os dias - quantos minutos por artista, que m\u00fasicas saltas, os teus padr\u00f5es por dia da semana.",
    objQ3: "\"Precisa do meu login do Spotify?\"",
    objA3: "N\u00e3o. O SpoTracker l\u00ea o t\u00edtulo da janela do Spotify para detetar o que est\u00e1 a tocar. Sem API keys, sem OAuth, sem passwords. Funciona com contas Free e Premium.",
    objQ4: "\"Vai deixar o meu PC mais lento?\"",
    objA4: "Usa ~15 MB RAM e 0% CPU. Para compara\u00e7\u00e3o, um \u00fanico separador do Chrome usa 5-10x mais. Nem vais notar que est\u00e1 a correr.",
    proofTitle: "Constru\u00eddo de forma aberta",
    proofSub: "Tudo sobre o SpoTracker \u00e9 transparente e gratuito.",
    proofLabel1: "C\u00f3digo open source",
    proofLabel2: "Dados enviados para a cloud",
    proofLabel3: "Para sempre, sem planos pagos",
    proofValue3: "Gr\u00e1tis",
    faqTitle: "Perguntas frequentes",
    faqSub: "Respostas r\u00e1pidas \u00e0s restantes quest\u00f5es.",
    faqQ1: "Onde ficam os meus dados?",
    faqA1: "Na tua pasta Documentos em <code>C:\\Users\\&lt;tu&gt;\\Documents\\SpoTracker\\</code>. O hist\u00f3rico de escuta fica em <code>music-list.csv</code> e os relat\u00f3rios na subpasta <code>reports</code>.",
    faqQ2: "Regista corretamente quando ponho pausa?",
    faqA2: "Sim. O SpoTracker deteta quando o Spotify est\u00e1 em pausa e subtrai o tempo automaticamente. Tamb\u00e9m filtra plays curtos (menos de 20 segundos) nos relat\u00f3rios.",
    faqQ3: "Funciona no Mac ou Linux?",
    faqA3: "Atualmente apenas Windows (10 e 11). Usa APIs do Windows para ler t\u00edtulos de janela e mostrar o \u00edcone na system tray.",
    faqQ4: "Posso desinstalar completamente?",
    faqA4: "Sim, desinstala como qualquer app do Windows em Defini\u00e7\u00f5es \u2192 Aplica\u00e7\u00f5es. Os teus dados de escuta nos Documentos s\u00e3o preservados para n\u00e3o perderes o hist\u00f3rico.",
    faqQ5: "Como gero um relat\u00f3rio?",
    faqA5: "Clica com o bot\u00e3o direito no \u00edcone do SpoTracker na system tray (canto inferior direito) e seleciona \"Generate New Report\". O browser abre com os resultados.",
    ctaTitle: "As tuas estat\u00edsticas est\u00e3o \u00e0 espera",
    ctaSub: "Descobre o que a tua m\u00fasica diz sobre ti.",
    ctaCheck1: "Instala em 30 segundos",
    ctaCheck2: "Sem conta necess\u00e1ria",
    ctaCheck3: "Gr\u00e1tis para sempre",
    ctaBtn: "Download SpoTracker - \u00e9 gr\u00e1tis",
    founderTitle: "Porque constru\u00ed isto",
    founderP1: "Adoro m\u00fasica. Ou\u00e7o Spotify durante horas todos os dias. Mas n\u00e3o fazia ideia do que realmente ouvia - at\u00e9 o Wrapped sair em dezembro, e mesmo assim era apenas um resumo.",
    founderP2: "Queria saber os n\u00fameros reais. Quantos minutos passei com cada artista? Que m\u00fasicas saltei? Em que dias ou\u00e7o mais? E queria ver quando me apetecesse, n\u00e3o uma vez por ano.",
    founderP3: "Ent\u00e3o constru\u00ed o SpoTracker. Uma pequena app que corre em segundo plano, regista tudo localmente, e gera relat\u00f3rios bonitos a pedido. Sem cloud, sem contas, sem dados a sair do meu computador.",
    founderP4: "Se \u00e9s o tipo de pessoa que rev\u00ea os screenshots do Wrapped meses depois, isto \u00e9 para ti.",
    founderRole: "Programador & entusiasta de m\u00fasica",
    footer: "SpoTracker - Open source no <a href=\"https://github.com/andreferreira04/spoTracker\" target=\"_blank\" rel=\"noopener\">GitHub</a>. Feito com \u266a por Andr\u00e9 Ferreira."
  }
};

function setLang(lang) {
  var t = LOCALES[lang];
  if (!t) return;
  document.documentElement.lang = lang;
  document.title = t.pageTitle;
  var meta = document.querySelector("meta[name='description']");
  if (meta) meta.content = t.pageDescription;

  var ogTitle = document.querySelector("meta[property='og:title']");
  if (ogTitle) ogTitle.content = t.pageTitle;
  var ogDesc = document.querySelector("meta[property='og:description']");
  if (ogDesc) ogDesc.content = t.pageDescription;
  var ogLocale = document.querySelector("meta[property='og:locale']");
  if (ogLocale) ogLocale.content = lang === "pt" ? "pt_PT" : "en_US";

  var twTitle = document.querySelector("meta[name='twitter:title']");
  if (twTitle) twTitle.content = t.pageTitle;
  var twDesc = document.querySelector("meta[name='twitter:description']");
  if (twDesc) twDesc.content = t.pageDescription;

  document.querySelectorAll("[data-i18n]").forEach(function(el) {
    var key = el.getAttribute("data-i18n");
    if (t[key] == null) return;
    if (el.hasAttribute("data-i18n-html")) {
      el.innerHTML = t[key];
    } else {
      el.textContent = t[key];
    }
  });
  document.querySelectorAll(".lang-btn").forEach(function(btn) {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });
  localStorage.setItem("spotracker-lang", lang);
}

document.addEventListener("DOMContentLoaded", function() {
  var saved = localStorage.getItem("spotracker-lang");
  var browserLang = navigator.language.slice(0, 2);
  setLang(saved || (browserLang === "pt" ? "pt" : "en"));
});
