name: Build & Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile EXE (folder mode)
        run: |
          pyinstaller --noconsole --name SpoTracker music-register.py

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Build Installer
        run: |
          iscc SpoTracker.iss

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.ref_name  }}
          name: "SpoTracker Release ${{ github.ref_name  }}"
          files: |
            output/SpoTrackerInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
